/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test;

import com.dao.DBManager;
import com.models.MasterModel;
import com.placeholder.PlaceHolder;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mutaher Affan
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        
        //SETTING UP SCREEN
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        setTitle("Master Admin Login");
        setIcon();
        jPanel1.requestFocus();
        
        //SETTING UP PLACE HOLDERS
        this.Password_field.setEchoChar((char)0);
        PlaceHolders();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        user_name_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        minimize_panel = new javax.swing.JPanel();
        minimize_label = new javax.swing.JLabel();
        exit_panel = new javax.swing.JPanel();
        exit_label = new javax.swing.JLabel();
        login_label = new javax.swing.JLabel();
        Password_field = new javax.swing.JPasswordField();
        wrong_username_or_password_label = new javax.swing.JLabel();
        back_button_label = new javax.swing.JLabel();
        show_password_check_box = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(54, 33, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(107, 107, 190), 3));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        user_name_label.setBackground(new java.awt.Color(255, 255, 255));
        user_name_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user_name_label.setForeground(new java.awt.Color(255, 255, 255));
        user_name_label.setText("USER NAME :-");

        password_label.setBackground(new java.awt.Color(255, 255, 255));
        password_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password_label.setForeground(new java.awt.Color(255, 255, 255));
        password_label.setText("PASSWORD :-");

        username_input.setBackground(new java.awt.Color(54, 33, 80));
        username_input.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        username_input.setForeground(new java.awt.Color(255, 255, 255));
        username_input.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        username_input.setCaretColor(new java.awt.Color(255, 255, 255));
        username_input.setOpaque(false);
        username_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_inputKeyPressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(54, 33, 80));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(255, 255, 255)));

        minimize_panel.setBackground(new java.awt.Color(54, 33, 80));

        minimize_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_minus_math_filled_25px.png"))); // NOI18N
        minimize_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize_labelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout minimize_panelLayout = new javax.swing.GroupLayout(minimize_panel);
        minimize_panel.setLayout(minimize_panelLayout);
        minimize_panelLayout.setHorizontalGroup(
            minimize_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimize_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize_label))
        );
        minimize_panelLayout.setVerticalGroup(
            minimize_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimize_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize_label))
        );

        jPanel3.add(minimize_panel);

        exit_panel.setBackground(new java.awt.Color(54, 33, 80));
        exit_panel.setLayout(new javax.swing.BoxLayout(exit_panel, javax.swing.BoxLayout.LINE_AXIS));

        exit_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_multiply_filled_25px.png"))); // NOI18N
        exit_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_labelMouseExited(evt);
            }
        });
        exit_panel.add(exit_label);

        jPanel3.add(exit_panel);

        login_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_login_rounded_right_filled_35px_1.png"))); // NOI18N
        login_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_labelMouseExited(evt);
            }
        });

        Password_field.setBackground(new java.awt.Color(54, 33, 80));
        Password_field.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Password_field.setForeground(new java.awt.Color(255, 255, 255));
        Password_field.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        Password_field.setCaretColor(new java.awt.Color(255, 255, 255));
        Password_field.setOpaque(false);
        Password_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Password_fieldMouseClicked(evt);
            }
        });
        Password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_fieldActionPerformed(evt);
            }
        });
        Password_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Password_fieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Password_fieldKeyTyped(evt);
            }
        });

        wrong_username_or_password_label.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        wrong_username_or_password_label.setForeground(new java.awt.Color(255, 0, 102));

        back_button_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_left_arrow_50px.png"))); // NOI18N
        back_button_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_button_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_button_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_button_labelMouseExited(evt);
            }
        });

        show_password_check_box.setBackground(new java.awt.Color(54, 33, 80));
        show_password_check_box.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        show_password_check_box.setForeground(new java.awt.Color(255, 255, 255));
        show_password_check_box.setText("Show Password");
        show_password_check_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_password_check_boxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_button_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(user_name_label)
                    .addComponent(password_label))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(show_password_check_box))
                        .addGap(18, 18, 18)
                        .addComponent(login_label)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wrong_username_or_password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back_button_label)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login_label)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                        .addComponent(show_password_check_box)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrong_username_or_password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimize_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_labelMouseClicked

    private void exit_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_labelMouseClicked

    private void exit_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseEntered
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/close.png"));
        this.exit_label.setIcon(icon);
    }//GEN-LAST:event_exit_labelMouseEntered

    private void exit_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_multiply_filled_25px.png"));
        this.exit_label.setIcon(icon);
    }//GEN-LAST:event_exit_labelMouseExited

    private void minimize_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseEntered
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_minus_25px.png"));
        this.minimize_label.setIcon(icon);
    }//GEN-LAST:event_minimize_labelMouseEntered

    private void minimize_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_minus_math_filled_25px.png"));
        this.minimize_label.setIcon(icon);
    }//GEN-LAST:event_minimize_labelMouseExited

    private void login_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_labelMouseClicked
        // TODO add your handling code here:
        if(username_input.getText().equals("") || this.Password_field.getText().equals("") || username_input.getText().equals("Enter Username") || this.Password_field.getText().equals("Enter Password"))
            {
                JOptionPane.showMessageDialog(rootPane, "Please Fill Fields");
            }
            else 
            {
                login();
            }
    }//GEN-LAST:event_login_labelMouseClicked

    private void Password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_fieldActionPerformed

    private void Password_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Password_fieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            if(username_input.getText().equals("") || this.Password_field.getText().equals(""))
            {
                JOptionPane.showMessageDialog(rootPane, "Please Fill Fields");
            }
            else 
            {
                login();
            }
        }
    }//GEN-LAST:event_Password_fieldKeyPressed

    private void login_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_labelMouseEntered
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_login_rounded_right_filled_35px_2.png"));
        this.login_label.setIcon(icon);
    }//GEN-LAST:event_login_labelMouseEntered

    private void login_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_labelMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_login_rounded_right_filled_35px_1.png"));
        this.login_label.setIcon(icon);
    }//GEN-LAST:event_login_labelMouseExited

    private void back_button_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button_labelMouseClicked
        // TODO add your handling code here:
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_back_button_labelMouseClicked

    private void back_button_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button_labelMouseEntered
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_left_arrow_50px_1.png"));
        this.back_button_label.setIcon(icon);
    }//GEN-LAST:event_back_button_labelMouseEntered

    private void back_button_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button_labelMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_left_arrow_50px.png"));
        this.back_button_label.setIcon(icon);
    }//GEN-LAST:event_back_button_labelMouseExited

    private void show_password_check_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_password_check_boxActionPerformed
        // TODO add your handling code here:
        if(show_password_check_box.isSelected())
        {
            this.Password_field.setEchoChar((char)0);
        }
        else
        {
            this.Password_field.setEchoChar('*');
        }
    }//GEN-LAST:event_show_password_check_boxActionPerformed

    private void username_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_inputKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            if(username_input.getText().equals("") || this.Password_field.getText().equals(""))
            {
                JOptionPane.showMessageDialog(rootPane, "Please Fill Fields");
            }
            else 
            {
                login();
            }
        }
    }//GEN-LAST:event_username_inputKeyPressed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        if (this.Password_field.getText().equals(""))
        {
        this.Password_field.setEchoChar((char)0);
        PlaceHolders();
        jPanel1.requestFocus();
        }
        else if (username_input.getText().equals(""))
        {
            PlaceHolders();
            jPanel1.requestFocus();
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void Password_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_fieldMouseClicked
        // TODO add your handling code here:
        this.Password_field.setEchoChar('*');
    }//GEN-LAST:event_Password_fieldMouseClicked

    private void Password_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Password_fieldKeyTyped
        // TODO add your handling code here:
        this.Password_field.setEchoChar('*');
    }//GEN-LAST:event_Password_fieldKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Admin().setVisible(true);
//            }
//        });
//    }
    
                   //     ********------LOGGING IN MASTER USER---MANAGEMENT---METHOD------********
    
  private void login() {
        MasterModel masterModel = DBManager.getUsername_and_Password();
        String username = new String(username_input.getText());
        String password = new String(this.Password_field.getPassword());
        if(masterModel.getUsername().equals(username) && masterModel.getPassword().equals(password)) 
        {
            Admin_Frame admin_Frame = new Admin_Frame();
            admin_Frame.setVisible(true);
            setVisible(false);
        }
           
        else 
        {
            wrong_username_or_password_label.setText("Please enter a Valid Username and Password.");
            username_input.setText("");
            this.Password_field.setText("");
        }
        
    }
  
  // SETTING UP WINDOWS ICON
  
  private void setIcon()
  {
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/images/application_logo.png")));
  }
  
   // SETTING UP PLACE HOLDERS METHODS
       
  private void PlaceHolders()
  {
      PlaceHolder holder = new PlaceHolder(username_input, "Enter Username");
      PlaceHolder holder2 = new PlaceHolder(Password_field, "Enter Password");
      holder.setColorSimple(Color.WHITE);
      holder.setFont("Verdana");
      holder2.setColorSimple(Color.WHITE);
      holder2.setFont("Verdana");    
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password_field;
    private javax.swing.JLabel back_button_label;
    private javax.swing.JLabel exit_label;
    private javax.swing.JPanel exit_panel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel login_label;
    private javax.swing.JLabel minimize_label;
    private javax.swing.JPanel minimize_panel;
    private javax.swing.JLabel password_label;
    private javax.swing.JCheckBox show_password_check_box;
    private javax.swing.JLabel user_name_label;
    private javax.swing.JTextField username_input;
    private javax.swing.JLabel wrong_username_or_password_label;
    // End of variables declaration//GEN-END:variables
}
