/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test;

import com.dao.DBManager;
import com.models.Mobile_DataModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mutaher Affan
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        //SETTING UP SCREEN
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        setTitle("Mobile Management");
        setIcon();
        
        //SETTING UP JTABLE HEADERS LOOK
        
        show_mobile_data_Table.setRowHeight(30);
        show_mobile_data_Table.getTableHeader().setForeground(Color.DARK_GRAY);
        show_mobile_data_Table.getTableHeader().setFont(new Font("Berlin Sans FB", Font.PLAIN, 12));
        showMobileData();
        
        //SETTING UP COLOR INPUT AS DISABLE AT RUN TIME
        
        color_input.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator7 = new javax.swing.JSeparator();
        bg_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        show_mobile_data_Table = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        logo_label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cost_input = new javax.swing.JTextField();
        imei_input = new javax.swing.JTextField();
        sale_input = new javax.swing.JTextField();
        brand_input = new javax.swing.JTextField();
        condition_combo = new javax.swing.JComboBox<>();
        Date_jcalender = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        delete_button = new keeptoo.KButton();
        update_button = new keeptoo.KButton();
        add_button = new keeptoo.KButton();
        jLabel8 = new javax.swing.JLabel();
        model_input = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        color_combo = new javax.swing.JComboBox<>();
        total_number_of_mobiles_label = new javax.swing.JLabel();
        count_mobiles_label = new javax.swing.JLabel();
        color_check_box = new javax.swing.JCheckBox();
        color_input = new javax.swing.JTextField();
        reset_button = new keeptoo.KButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        minimize_panel = new javax.swing.JPanel();
        minimize_label = new javax.swing.JLabel();
        exit_panel = new javax.swing.JPanel();
        exit_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        back_button_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg_panel.setBackground(new java.awt.Color(54, 33, 80));
        bg_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 107, 190), 3, true));
        bg_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 33, 80));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Mobile Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        show_mobile_data_Table = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex , int colIndex)
            {
                return false;
            }
        };
        show_mobile_data_Table.setBackground(new java.awt.Color(54, 33, 80));
        show_mobile_data_Table.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        show_mobile_data_Table.setForeground(new java.awt.Color(255, 255, 255));
        show_mobile_data_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STOCK ID", "MODEL NO", "BRAND", "IMEI NO", "COST PRICE", "SALE PRICE", "CONDITION", "DATE", "COLOR", "MODIFIED BYl"
            }
        ));
        show_mobile_data_Table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show_mobile_data_Table.setGridColor(new java.awt.Color(255, 255, 255));
        show_mobile_data_Table.setRowHeight(20);
        show_mobile_data_Table.setSelectionBackground(new java.awt.Color(102, 102, 255));
        show_mobile_data_Table.getTableHeader().setReorderingAllowed(false);
        show_mobile_data_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_mobile_data_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(show_mobile_data_Table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );

        bg_panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 146, 580, 600));

        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bg_panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 118, 1130, 10));

        logo_label.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        logo_label.setForeground(new java.awt.Color(255, 255, 255));
        logo_label.setText("MOBILE MANAGEMENT");
        logo_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logo_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logo_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logo_labelMouseExited(evt);
            }
        });
        bg_panel.add(logo_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(54, 33, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Mobile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MODEL NO :-");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BRAND :-");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("COST PRICE :-");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SALE PRICE :-");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONDITION :-");

        cost_input.setBackground(new java.awt.Color(54, 33, 80));
        cost_input.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cost_input.setForeground(new java.awt.Color(255, 255, 255));
        cost_input.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        cost_input.setCaretColor(new java.awt.Color(255, 255, 255));
        cost_input.setOpaque(false);

        imei_input.setBackground(new java.awt.Color(54, 33, 80));
        imei_input.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        imei_input.setForeground(new java.awt.Color(255, 255, 255));
        imei_input.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        imei_input.setCaretColor(new java.awt.Color(255, 255, 255));
        imei_input.setOpaque(false);

        sale_input.setBackground(new java.awt.Color(54, 33, 80));
        sale_input.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        sale_input.setForeground(new java.awt.Color(255, 255, 255));
        sale_input.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        sale_input.setCaretColor(new java.awt.Color(255, 255, 255));
        sale_input.setOpaque(false);

        brand_input.setBackground(new java.awt.Color(54, 33, 80));
        brand_input.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        brand_input.setForeground(new java.awt.Color(255, 255, 255));
        brand_input.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        brand_input.setCaretColor(new java.awt.Color(255, 255, 255));
        brand_input.setOpaque(false);

        condition_combo.setBackground(getBackground());
        condition_combo.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        condition_combo.setForeground(new java.awt.Color(102, 102, 102));
        condition_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECT---", "NEW", "USED" }));
        condition_combo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        Date_jcalender.setDateFormatString(" yyyy,MMM,d");
        Date_jcalender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATE :-");

        delete_button.setText("DELETE");
        delete_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        delete_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_buttonMouseClicked(evt);
            }
        });

        update_button.setForeground(new java.awt.Color(51, 51, 51));
        update_button.setText("UPDATE");
        update_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        update_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_buttonMouseClicked(evt);
            }
        });

        add_button.setText("ADD");
        add_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_buttonMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("IMEI NO :-");

        model_input.setBackground(new java.awt.Color(54, 33, 80));
        model_input.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        model_input.setForeground(new java.awt.Color(255, 255, 255));
        model_input.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        model_input.setCaretColor(new java.awt.Color(255, 255, 255));
        model_input.setOpaque(false);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("COLOR :-");

        color_combo.setBackground(getBackground());
        color_combo.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        color_combo.setForeground(new java.awt.Color(102, 102, 102));
        color_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECT---", "BLUE", "BLACK", "WHITE", "GOLD", "METALLIC", "GREY" }));
        color_combo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        total_number_of_mobiles_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_number_of_mobiles_label.setForeground(new java.awt.Color(255, 255, 255));

        count_mobiles_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        count_mobiles_label.setForeground(new java.awt.Color(255, 51, 102));

        color_check_box.setBackground(new java.awt.Color(54, 33, 80));
        color_check_box.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        color_check_box.setForeground(new java.awt.Color(255, 255, 255));
        color_check_box.setText("Others");
        color_check_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_check_boxActionPerformed(evt);
            }
        });

        color_input.setBackground(new java.awt.Color(54, 33, 80));
        color_input.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        color_input.setForeground(new java.awt.Color(255, 255, 255));
        color_input.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        color_input.setCaretColor(new java.awt.Color(255, 255, 255));

        reset_button.setForeground(new java.awt.Color(51, 51, 51));
        reset_button.setText("RESET");
        reset_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        reset_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(total_number_of_mobiles_label, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(count_mobiles_label, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Date_jcalender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cost_input)
                                .addComponent(imei_input)
                                .addComponent(sale_input)
                                .addComponent(brand_input)
                                .addComponent(condition_combo, 0, 152, Short.MAX_VALUE)
                                .addComponent(model_input, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(color_check_box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(color_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(color_input)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(model_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(brand_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imei_input, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cost_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sale_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(condition_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_jcalender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(color_check_box))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(color_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(color_input, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(total_number_of_mobiles_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(count_mobiles_label, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        bg_panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 146, 490, 600));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        bg_panel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 146, 13, 600));

        jPanel3.setBackground(new java.awt.Color(54, 33, 80));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(255, 255, 255)));

        minimize_panel.setBackground(new java.awt.Color(54, 33, 80));

        minimize_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_minus_math_filled_25px.png"))); // NOI18N
        minimize_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize_labelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout minimize_panelLayout = new javax.swing.GroupLayout(minimize_panel);
        minimize_panel.setLayout(minimize_panelLayout);
        minimize_panelLayout.setHorizontalGroup(
            minimize_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimize_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize_label))
        );
        minimize_panelLayout.setVerticalGroup(
            minimize_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimize_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize_label))
        );

        jPanel3.add(minimize_panel);

        exit_panel.setBackground(new java.awt.Color(54, 33, 80));
        exit_panel.setLayout(new javax.swing.BoxLayout(exit_panel, javax.swing.BoxLayout.LINE_AXIS));

        exit_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_multiply_filled_25px.png"))); // NOI18N
        exit_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_labelMouseExited(evt);
            }
        });
        exit_panel.add(exit_label);

        jPanel3.add(exit_panel);

        bg_panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_phonelink_setup_70px.png"))); // NOI18N
        bg_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        back_button_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_circled_left_2_filled_50px.png"))); // NOI18N
        back_button_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_button_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_button_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_button_labelMouseExited(evt);
            }
        });
        bg_panel.add(back_button_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_labelMouseClicked

    private void minimize_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_labelMouseClicked

    private void logo_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo_labelMouseEntered
        // TODO add your handling code here:
        setColor(logo_label);
    }//GEN-LAST:event_logo_labelMouseEntered

    private void logo_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo_labelMouseExited
        // TODO add your handling code here:
        resetColor(logo_label);
    }//GEN-LAST:event_logo_labelMouseExited

    private void add_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseClicked
        // TODO add your handling code here:
        if(imei_input.getText().isEmpty() || brand_input.getText().isEmpty() || cost_input.getText().isEmpty() || sale_input.getText().isEmpty() || (Date_jcalender.getDate() == null) || (condition_combo.getSelectedIndex() == 0) || (color_combo.isEnabled() == true) && (color_combo.getSelectedIndex() == 0) || (color_input.isEnabled() == true) && (color_input.getText().isEmpty() ) ) 
        {
            JOptionPane.showMessageDialog(rootPane, "Please Fill Fields");
        }
        else 
        {
            checkValidation();
        }
    }//GEN-LAST:event_add_buttonMouseClicked

    private void show_mobile_data_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_mobile_data_TableMouseClicked
        // TODO add your handling code here:
        model_input.setText( (String) show_mobile_data_Table.getValueAt(show_mobile_data_Table.getSelectedRow(), 1));
        brand_input.setText( (String) show_mobile_data_Table.getValueAt(show_mobile_data_Table.getSelectedRow(), 2));
        imei_input.setText( (String) show_mobile_data_Table.getValueAt(show_mobile_data_Table.getSelectedRow(), 3));
        cost_input.setText( (String) show_mobile_data_Table.getValueAt(show_mobile_data_Table.getSelectedRow(), 4));
        sale_input.setText( (String) show_mobile_data_Table.getValueAt(show_mobile_data_Table.getSelectedRow(), 5));

        String i = show_mobile_data_Table.getValueAt(show_mobile_data_Table.getSelectedRow(), 6).toString(); 
        if( i.equalsIgnoreCase("NEW"))
        {
            condition_combo.setSelectedIndex(1);
        }
        else if (i.equalsIgnoreCase("USED"))
        {
            condition_combo.setSelectedIndex(2);
        }
        
        Date_jcalender.setDate( (Date) show_mobile_data_Table.getValueAt(show_mobile_data_Table.getSelectedRow(), 7) );
        
        String j = show_mobile_data_Table.getValueAt(show_mobile_data_Table.getSelectedRow(), 8).toString();
        if( j.equalsIgnoreCase("BLUE"))
        {
            color_input.setText("");
            color_combo.setSelectedIndex(1);    
        }
        else if (j.equalsIgnoreCase("BLACK"))
        {
            color_input.setText("");
            color_combo.setSelectedIndex(2);
        }
        else if (j.equalsIgnoreCase("WHITE"))
        {
            color_input.setText("");
            color_combo.setSelectedIndex(3);
        }
        else if (j.equalsIgnoreCase("GOLD"))
        {
            color_input.setText("");
            color_combo.setSelectedIndex(4);
        }
        else if (j.equalsIgnoreCase("METALLIC"))
        {
            color_input.setText("");
            color_combo.setSelectedIndex(5);
        }
        else if (j.equalsIgnoreCase("GREY"))
        {
            color_input.setText("");
            color_combo.setSelectedIndex(6);
        }
        else
        {
            color_combo.setSelectedIndex(0);
            color_input.setText(show_mobile_data_Table.getValueAt(show_mobile_data_Table.getSelectedRow(), 8).toString());
        }
            
    }//GEN-LAST:event_show_mobile_data_TableMouseClicked

    private void delete_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_buttonMouseClicked
        // TODO add your handling code here:
        deleteMobile();
        EmptyFields();
    }//GEN-LAST:event_delete_buttonMouseClicked

    private void update_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_buttonMouseClicked
        // TODO add your handling code here:
        updateMobile();
        EmptyFields();
    }//GEN-LAST:event_update_buttonMouseClicked

    private void back_button_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button_labelMouseClicked
        // TODO add your handling code here:
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_back_button_labelMouseClicked

    private void exit_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseEntered
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/close.png"));
        this.exit_label.setIcon(icon);
    }//GEN-LAST:event_exit_labelMouseEntered

    private void exit_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_multiply_filled_25px.png"));
        this.exit_label.setIcon(icon);
    }//GEN-LAST:event_exit_labelMouseExited

    private void minimize_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseEntered
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_minus_25px.png"));
        this.minimize_label.setIcon(icon);
    }//GEN-LAST:event_minimize_labelMouseEntered

    private void minimize_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_minus_math_filled_25px.png"));
        this.minimize_label.setIcon(icon);
    }//GEN-LAST:event_minimize_labelMouseExited

    private void color_check_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_check_boxActionPerformed
        // TODO add your handling code here:
        if(color_check_box.isSelected())
        {
            color_combo.setEnabled(false);
            color_input.setEnabled(true);
        }
        else
        {
            color_combo.setEnabled(true);
            color_input.setEnabled(false);
        }
        
    }//GEN-LAST:event_color_check_boxActionPerformed

    private void back_button_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button_labelMouseEntered
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_circled_left_2_filled_50px_1.png"));
        this.back_button_label.setIcon(icon);
    }//GEN-LAST:event_back_button_labelMouseEntered

    private void back_button_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button_labelMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_circled_left_2_filled_50px.png"));
        this.back_button_label.setIcon(icon);
    }//GEN-LAST:event_back_button_labelMouseExited

    private void reset_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_buttonMouseClicked
        // TODO add your handling code here:
        EmptyFields();
    }//GEN-LAST:event_reset_buttonMouseClicked

    public void setColor(JLabel label) 
    {
        label.setForeground(new java.awt.Color(231, 33, 99));
    }
    
    public void resetColor(JLabel label) 
    {
        label.setForeground(new java.awt.Color(255,255,255));
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home().setVisible(true);
//            }
//        });
//    }
    
    //     ********------MOBILE DATA---MANAGEMENT---METHOD------********
    
    //SHOWING UNSOLD MOBILE DATA
      private void showMobileData(){
         List<Mobile_DataModel> mobile_DataModels = DBManager.getAllData();
         
         int count = mobile_DataModels.size();
         if(count > 0)
         {
             total_number_of_mobiles_label.setText("Total Number Of Mobiles :-");
             Border border = BorderFactory.createLineBorder(Color.WHITE, 2);
             count_mobiles_label.setBorder(border);
             count_mobiles_label.setText(" "+Integer.toString(count));
         }
         
         else
         {
            total_number_of_mobiles_label.setText("");
            count_mobiles_label.setText("");
           JOptionPane.showMessageDialog(rootPane, "You have no Mobile data in your Database.");  
         }
         
         DefaultTableModel model = (DefaultTableModel)show_mobile_data_Table.getModel();
         Object[] row = new Object[10];
         for(int i = 0;i<mobile_DataModels.size();i++){
             
            row[0] = mobile_DataModels.get(i).getStock_id();
            row[1] = mobile_DataModels.get(i).getModel_no();
            row[2] = mobile_DataModels.get(i).getBrand();
            row[3] = mobile_DataModels.get(i).getImei_no();
            row[4] = mobile_DataModels.get(i).getCost_price();
            row[5] = mobile_DataModels.get(i).getSale_price();
            row[6] = mobile_DataModels.get(i).getCondition();
            row[7] = mobile_DataModels.get(i).getDate();
            row[8] = mobile_DataModels.get(i).getColor();
            row[9] = mobile_DataModels.get(i).getModified_by();
            model.addRow(row);
         }
    }
     
      
      //ADDING MOBILE DATA
      private void addmobile(){
        Mobile_DataModel mobile_DataModel = new Mobile_DataModel();
        String model_no = new String(model_input.getText()).toUpperCase();
        mobile_DataModel.setModel_no(model_no);
        String brand = new String(brand_input.getText()).toUpperCase();
        mobile_DataModel.setBrand(brand);
        String imei = new String(imei_input.getText()).toUpperCase();
        mobile_DataModel.setImei_no(imei);
        String cost_price = new String(cost_input.getText()).toUpperCase();
        mobile_DataModel.setCost_price(cost_price);
        String sale_price = new String(sale_input.getText()).toUpperCase();
        mobile_DataModel.setSale_price(sale_price);
        
        String condition = condition_combo.getSelectedItem().toString();
        mobile_DataModel.setCondition(condition);
        
        mobile_DataModel.setDate(Date_jcalender.getDate());
        
        if(color_combo.isEnabled()== true && color_input.isEnabled() == false) 
        {
            String color = color_combo.getSelectedItem().toString();
            mobile_DataModel.setColor(color);
        }
        else if(color_combo.isEnabled()== false && color_input.isEnabled() == true)
        {
            String color = new String(color_input.getText()).toUpperCase();
            mobile_DataModel.setColor(color);
        }
        
        
        int row = DBManager.addMobile(mobile_DataModel);
        
        if (row > 0)
        {
                JOptionPane.showMessageDialog(null, "RECORD ADDED SUCCESSFULLY");
                DefaultTableModel model = (DefaultTableModel) show_mobile_data_Table.getModel();
                model.setRowCount(0);
                showMobileData();
        }
        
        else
        {
                JOptionPane.showMessageDialog(null, "RECORD NOT ADDED");
        }
        
    }
      
      //DELETING MOBILE DATA
      private void deleteMobile(){
        String imei_no = imei_input.getText() ;
        int row = DBManager.deleteMobile(imei_no);
        if (row > 0){
                JOptionPane.showMessageDialog(null, "RECORD DELETED SUCCESSFULLY");
                DefaultTableModel model = (DefaultTableModel) show_mobile_data_Table.getModel();
                model.setRowCount(0);
                showMobileData();
            }
            else{
                JOptionPane.showMessageDialog(null, "RECORD NOT DELETED");
            }
    }
      
      //UPDATING MOBILE DATA
       private void updateMobile(){
        Mobile_DataModel mobile_DataModel = new Mobile_DataModel();
        String model_no = new String(model_input.getText()).toUpperCase();
        mobile_DataModel.setModel_no(model_no);
        String brand = new String(brand_input.getText()).toUpperCase();
        mobile_DataModel.setBrand(brand);
        String imei = new String(imei_input.getText()).toUpperCase();
        mobile_DataModel.setImei_no(imei);
        String cost_price = new String(cost_input.getText()).toUpperCase();
        mobile_DataModel.setCost_price(cost_price);
        String sale_price = new String(sale_input.getText()).toUpperCase();
        mobile_DataModel.setSale_price(sale_price);
       
        String condition = condition_combo.getSelectedItem().toString();
        mobile_DataModel.setCondition(condition);
        
        mobile_DataModel.setDate(Date_jcalender.getDate());
        
        if(color_combo.isEnabled()== true && color_input.isEnabled() == false) 
        {
            String color = color_combo.getSelectedItem().toString();
            mobile_DataModel.setColor(color);
        }
        else if(color_combo.isEnabled()== false && color_input.isEnabled() == true)
        {
            String color = new String(color_input.getText()).toUpperCase();
            mobile_DataModel.setColor(color);
        }
        
        int row = DBManager.updateMobile(mobile_DataModel,imei_input.getText());
        if (row > 0)
        {
               JOptionPane.showMessageDialog(null, "RECORD UPDATED SUCCESSFULLY");
               DefaultTableModel model = (DefaultTableModel) show_mobile_data_Table.getModel();
               model.setRowCount(0);
               showMobileData();
        }
            else
        {
               JOptionPane.showMessageDialog(null, "RECORD NOT UPDATED");
        }
    }
       
    
    //CHECKING IMEI NO IS ALREADY IN DB OR NOT
      private void checkValidation(){
         List<Mobile_DataModel> mobile_DataModels = DBManager.getAllMobilesByIMEI(imei_input.getText());      
         int count = mobile_DataModels.size();
         if(count == 0)
         {
             addmobile();
             EmptyFields();
         }
         
         else
         {
            JOptionPane.showMessageDialog(rootPane, "Entered IMEI is already present in Database,\nPlease Enter a Valid IMEI NO.");
            imei_input.setText("");
         }
      }
       
       
       //EMPTY FIELDS
       private void EmptyFields()
       {
            model_input.setText("");
            brand_input.setText("");
            imei_input.setText("");
            cost_input.setText("");
            sale_input.setText("");
            condition_combo.setSelectedIndex(0);
            color_combo.setSelectedIndex(0);
            color_input.setText("");
            Date_jcalender.setDate(null);
       }
       
        // SETTING UP WINDOWS ICON
       private void setIcon() 
        {
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/images/application_logo.png")));
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_jcalender;
    private keeptoo.KButton add_button;
    private javax.swing.JLabel back_button_label;
    private javax.swing.JPanel bg_panel;
    private javax.swing.JTextField brand_input;
    private javax.swing.JCheckBox color_check_box;
    private javax.swing.JComboBox<String> color_combo;
    private javax.swing.JTextField color_input;
    private javax.swing.JComboBox<String> condition_combo;
    private javax.swing.JTextField cost_input;
    private javax.swing.JLabel count_mobiles_label;
    private keeptoo.KButton delete_button;
    private javax.swing.JLabel exit_label;
    private javax.swing.JPanel exit_panel;
    private javax.swing.JTextField imei_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel logo_label;
    private javax.swing.JLabel minimize_label;
    private javax.swing.JPanel minimize_panel;
    private javax.swing.JTextField model_input;
    private keeptoo.KButton reset_button;
    private javax.swing.JTextField sale_input;
    private javax.swing.JTable show_mobile_data_Table;
    private javax.swing.JLabel total_number_of_mobiles_label;
    private keeptoo.KButton update_button;
    // End of variables declaration//GEN-END:variables
}
