/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Mutaher Affan
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        
        //SETTING UP SCREEN
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        setTitle("Main Menu");
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        logo_label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        minimize_panel = new javax.swing.JPanel();
        minimize_label = new javax.swing.JLabel();
        exit_panel = new javax.swing.JPanel();
        exit_label = new javax.swing.JLabel();
        search_by_model_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        search_by_imei_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        admin_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        management_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sign_out_label = new javax.swing.JLabel();
        sold_mobiles_record_panel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        profit_and_monthly_record_panel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(54, 33, 80));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 107, 190), 3, true));

        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        logo_label.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        logo_label.setForeground(new java.awt.Color(255, 255, 255));
        logo_label.setText("ARSALAN'S MOBILE SHOP");
        logo_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logo_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logo_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logo_labelMouseExited(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(54, 33, 80));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(255, 255, 255)));

        minimize_panel.setBackground(new java.awt.Color(54, 33, 80));

        minimize_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_minus_math_filled_25px.png"))); // NOI18N
        minimize_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize_labelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout minimize_panelLayout = new javax.swing.GroupLayout(minimize_panel);
        minimize_panel.setLayout(minimize_panelLayout);
        minimize_panelLayout.setHorizontalGroup(
            minimize_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimize_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize_label))
        );
        minimize_panelLayout.setVerticalGroup(
            minimize_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimize_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize_label))
        );

        jPanel3.add(minimize_panel);

        exit_panel.setBackground(new java.awt.Color(54, 33, 80));
        exit_panel.setLayout(new javax.swing.BoxLayout(exit_panel, javax.swing.BoxLayout.LINE_AXIS));

        exit_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_multiply_filled_25px.png"))); // NOI18N
        exit_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_labelMouseExited(evt);
            }
        });
        exit_panel.add(exit_label);

        jPanel3.add(exit_panel);

        search_by_model_panel.setBackground(new java.awt.Color(64, 43, 100));
        search_by_model_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_by_model_panel.setPreferredSize(new java.awt.Dimension(215, 158));
        search_by_model_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_by_model_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search_by_model_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search_by_model_panelMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_search_more_50px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Search By Model-NO");

        javax.swing.GroupLayout search_by_model_panelLayout = new javax.swing.GroupLayout(search_by_model_panel);
        search_by_model_panel.setLayout(search_by_model_panelLayout);
        search_by_model_panelLayout.setHorizontalGroup(
            search_by_model_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_by_model_panelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_by_model_panelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(46, 46, 46))
        );
        search_by_model_panelLayout.setVerticalGroup(
            search_by_model_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_by_model_panelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        search_by_imei_panel.setBackground(new java.awt.Color(64, 43, 100));
        search_by_imei_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_by_imei_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_by_imei_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search_by_imei_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search_by_imei_panelMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_view_file_50px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Search By IMEI");

        javax.swing.GroupLayout search_by_imei_panelLayout = new javax.swing.GroupLayout(search_by_imei_panel);
        search_by_imei_panel.setLayout(search_by_imei_panelLayout);
        search_by_imei_panelLayout.setHorizontalGroup(
            search_by_imei_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_by_imei_panelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_by_imei_panelLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(84, 84, 84))
        );
        search_by_imei_panelLayout.setVerticalGroup(
            search_by_imei_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_by_imei_panelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        admin_panel.setBackground(new java.awt.Color(64, 43, 100));
        admin_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admin_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                admin_panelMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_admin_settings_male_50px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Admin");

        javax.swing.GroupLayout admin_panelLayout = new javax.swing.GroupLayout(admin_panel);
        admin_panel.setLayout(admin_panelLayout);
        admin_panelLayout.setHorizontalGroup(
            admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_panelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        admin_panelLayout.setVerticalGroup(
            admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_panelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        management_panel.setBackground(new java.awt.Color(64, 43, 100));
        management_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        management_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                management_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                management_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                management_panelMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_google_mobile_filled_50px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mobile Management");

        javax.swing.GroupLayout management_panelLayout = new javax.swing.GroupLayout(management_panel);
        management_panel.setLayout(management_panelLayout);
        management_panelLayout.setHorizontalGroup(
            management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(management_panelLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, management_panelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, management_panelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(46, 46, 46))))
        );
        management_panelLayout.setVerticalGroup(
            management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(management_panelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_google_home_70px_1.png"))); // NOI18N

        sign_out_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_safe_out_60px.png"))); // NOI18N
        sign_out_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sign_out_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_out_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sign_out_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sign_out_labelMouseExited(evt);
            }
        });

        sold_mobiles_record_panel.setBackground(new java.awt.Color(64, 43, 100));
        sold_mobiles_record_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sold_mobiles_record_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sold_mobiles_record_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sold_mobiles_record_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sold_mobiles_record_panelMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_details_pane_50px.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Sold Mobiles Record");

        javax.swing.GroupLayout sold_mobiles_record_panelLayout = new javax.swing.GroupLayout(sold_mobiles_record_panel);
        sold_mobiles_record_panel.setLayout(sold_mobiles_record_panelLayout);
        sold_mobiles_record_panelLayout.setHorizontalGroup(
            sold_mobiles_record_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sold_mobiles_record_panelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sold_mobiles_record_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(84, 84, 84))
        );
        sold_mobiles_record_panelLayout.setVerticalGroup(
            sold_mobiles_record_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sold_mobiles_record_panelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        profit_and_monthly_record_panel.setBackground(new java.awt.Color(64, 43, 100));
        profit_and_monthly_record_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profit_and_monthly_record_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profit_and_monthly_record_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profit_and_monthly_record_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profit_and_monthly_record_panelMouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_mobile_payment_50px.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Profit and Monthly Record");

        javax.swing.GroupLayout profit_and_monthly_record_panelLayout = new javax.swing.GroupLayout(profit_and_monthly_record_panel);
        profit_and_monthly_record_panel.setLayout(profit_and_monthly_record_panelLayout);
        profit_and_monthly_record_panelLayout.setHorizontalGroup(
            profit_and_monthly_record_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profit_and_monthly_record_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(82, 82, 82))
            .addGroup(profit_and_monthly_record_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profit_and_monthly_record_panelLayout.setVerticalGroup(
            profit_and_monthly_record_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profit_and_monthly_record_panelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(sign_out_label)
                .addGap(215, 215, 215)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(logo_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(management_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sold_mobiles_record_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(search_by_model_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profit_and_monthly_record_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_by_imei_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(logo_label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(sign_out_label))))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_by_model_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(management_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_by_imei_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sold_mobiles_record_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profit_and_monthly_record_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profit_and_monthly_record_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profit_and_monthly_record_panelMouseExited
        // TODO add your handling code here:
        resetColor(profit_and_monthly_record_panel);
    }//GEN-LAST:event_profit_and_monthly_record_panelMouseExited

    private void profit_and_monthly_record_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profit_and_monthly_record_panelMouseEntered
        // TODO add your handling code here:
        setColor(profit_and_monthly_record_panel);
    }//GEN-LAST:event_profit_and_monthly_record_panelMouseEntered

    private void profit_and_monthly_record_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profit_and_monthly_record_panelMouseClicked
        // TODO add your handling code here:
        Profit_Record_Frame frame = new Profit_Record_Frame();
        frame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_profit_and_monthly_record_panelMouseClicked

    private void sold_mobiles_record_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sold_mobiles_record_panelMouseExited
        // TODO add your handling code here:
        resetColor(sold_mobiles_record_panel);
    }//GEN-LAST:event_sold_mobiles_record_panelMouseExited

    private void sold_mobiles_record_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sold_mobiles_record_panelMouseEntered
        // TODO add your handling code here:
        setColor(sold_mobiles_record_panel);
    }//GEN-LAST:event_sold_mobiles_record_panelMouseEntered

    private void sold_mobiles_record_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sold_mobiles_record_panelMouseClicked
        // TODO add your handling code here:
        Sold_Mobiles_Frame frame = new Sold_Mobiles_Frame();
        frame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_sold_mobiles_record_panelMouseClicked

    private void sign_out_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_out_labelMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_safe_out_60px.png"));
        this.sign_out_label.setIcon(icon);
    }//GEN-LAST:event_sign_out_labelMouseExited

    private void sign_out_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_out_labelMouseEntered
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_safe_out_60px_1.png"));
        this.sign_out_label.setIcon(icon);
    }//GEN-LAST:event_sign_out_labelMouseEntered

    private void sign_out_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_out_labelMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_sign_out_labelMouseClicked

    private void management_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_management_panelMouseExited
        // TODO add your handling code here:
        resetColor(management_panel);
    }//GEN-LAST:event_management_panelMouseExited

    private void management_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_management_panelMouseEntered
        // TODO add your handling code here:
        setColor(management_panel);
    }//GEN-LAST:event_management_panelMouseEntered

    private void management_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_management_panelMouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_management_panelMouseClicked

    private void admin_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_panelMouseExited
        // TODO add your handling code here:
        resetColor(admin_panel);
    }//GEN-LAST:event_admin_panelMouseExited

    private void admin_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_panelMouseEntered
        // TODO add your handling code here:
        setColor(admin_panel);
    }//GEN-LAST:event_admin_panelMouseEntered

    private void admin_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_panelMouseClicked
        // TODO add your handling code here:
        Admin admin = new Admin();
        admin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_admin_panelMouseClicked

    private void search_by_imei_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_by_imei_panelMouseExited
        // TODO add your handling code here:
        resetColor(search_by_imei_panel);
    }//GEN-LAST:event_search_by_imei_panelMouseExited

    private void search_by_imei_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_by_imei_panelMouseEntered
        // TODO add your handling code here:
        setColor(search_by_imei_panel);
    }//GEN-LAST:event_search_by_imei_panelMouseEntered

    private void search_by_imei_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_by_imei_panelMouseClicked
        // TODO add your handling code here:
        Search_by_IMEI search_by_IMEI = new Search_by_IMEI();
        search_by_IMEI.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_search_by_imei_panelMouseClicked

    private void search_by_model_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_by_model_panelMouseExited
        // TODO add your handling code here:
        resetColor(search_by_model_panel);
    }//GEN-LAST:event_search_by_model_panelMouseExited

    private void search_by_model_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_by_model_panelMouseEntered
        // TODO add your handling code here:
        setColor(search_by_model_panel);
    }//GEN-LAST:event_search_by_model_panelMouseEntered

    private void search_by_model_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_by_model_panelMouseClicked
        // TODO add your handling code here:
        Search_by_MODEL_no search_by_MODEL_no = new Search_by_MODEL_no();
        search_by_MODEL_no.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_search_by_model_panelMouseClicked

    private void exit_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_multiply_filled_25px.png"));
        this.exit_label.setIcon(icon);
    }//GEN-LAST:event_exit_labelMouseExited

    private void exit_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseEntered
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/close.png"));
        this.exit_label.setIcon(icon);
    }//GEN-LAST:event_exit_labelMouseEntered

    private void exit_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_labelMouseClicked

    private void minimize_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_minus_math_filled_25px.png"));
        this.minimize_label.setIcon(icon);
    }//GEN-LAST:event_minimize_labelMouseExited

    private void minimize_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseEntered
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_minus_25px.png"));
        this.minimize_label.setIcon(icon);
    }//GEN-LAST:event_minimize_labelMouseEntered

    private void minimize_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_labelMouseClicked

    private void logo_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo_labelMouseExited
        // TODO add your handling code here:
        resetLabelColor(logo_label);
    }//GEN-LAST:event_logo_labelMouseExited

    private void logo_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo_labelMouseEntered
        // TODO add your handling code here:
        setLabelColor(logo_label);
    }//GEN-LAST:event_logo_labelMouseEntered

    public void setColor(JPanel panel) 
    {
        panel.setBackground(new java.awt.Color(85, 55, 118));
    }
    
    public void resetColor(JPanel panel) 
    {
        panel.setBackground(new java.awt.Color(64,43,100));
    }
    
     public void setLabelColor(JLabel label) 
    {
        label.setForeground(new java.awt.Color(231, 33, 99));
    }
    
    public void resetLabelColor(JLabel label) 
    {
        label.setForeground(new java.awt.Color(255,255,255));
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainMenu().setVisible(true);
//            }
//        });
//    }

     // SETTING UP WINDOWS ICON
        
       private void setIcon() 
        {
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/images/application_logo.png")));
        }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin_panel;
    private javax.swing.JLabel exit_label;
    private javax.swing.JPanel exit_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logo_label;
    private javax.swing.JPanel management_panel;
    private javax.swing.JLabel minimize_label;
    private javax.swing.JPanel minimize_panel;
    private javax.swing.JPanel profit_and_monthly_record_panel;
    private javax.swing.JPanel search_by_imei_panel;
    private javax.swing.JPanel search_by_model_panel;
    private javax.swing.JLabel sign_out_label;
    private javax.swing.JPanel sold_mobiles_record_panel;
    // End of variables declaration//GEN-END:variables
}
