/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test;

import com.dao.DBManager;
import com.models.Mobile_DataModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mutaher Affan
 */
public class Sold_Mobiles_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Sold_Mobiles_Frame
     */
    public Sold_Mobiles_Frame() {
        initComponents();
        
         //SETTING UP DISPLAY
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        setTitle("Sold Mobiles Record");
        setIcon();
        
        //SETTING UP JTABLE HEADERS LOOK
        
        show_mobile_data_Table.setRowHeight(30);
        show_mobile_data_Table.getTableHeader().setForeground(Color.DARK_GRAY);
        show_mobile_data_Table.getTableHeader().setFont(new Font("Berlin Sans FB", Font.PLAIN, 12));
        
        show_Sold_Mobile_Data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_panel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        show_mobile_data_Table = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        logo_label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        imei_input = new javax.swing.JTextField();
        search_button = new keeptoo.KButton();
        jLabel8 = new javax.swing.JLabel();
        total_number_of_mobiles_label = new javax.swing.JLabel();
        count_mobiles_label = new javax.swing.JLabel();
        delete_button = new keeptoo.KButton();
        refresh_button = new keeptoo.KButton();
        select_all_check_box = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        minimize_panel = new javax.swing.JPanel();
        minimize_label = new javax.swing.JLabel();
        exit_panel = new javax.swing.JPanel();
        exit_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        back_button_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg_panel1.setBackground(new java.awt.Color(54, 33, 80));
        bg_panel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(107, 107, 190), 3, true));
        bg_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(54, 33, 80));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Mobile Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        show_mobile_data_Table = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex , int colIndex)
            {
                return false;
            }
        };
        show_mobile_data_Table.setBackground(new java.awt.Color(54, 33, 80));
        show_mobile_data_Table.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        show_mobile_data_Table.setForeground(new java.awt.Color(255, 255, 255));
        show_mobile_data_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STOCK ID", "MODEL NO", "BRAND", "IMEI NO", "COST PRICE", "SALE PRICE", "CONDITION", "DATE", "COLOR", "MODIFIED BY"
            }
        ));
        show_mobile_data_Table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show_mobile_data_Table.setGridColor(new java.awt.Color(255, 255, 255));
        show_mobile_data_Table.setRowHeight(20);
        show_mobile_data_Table.setSelectionBackground(new java.awt.Color(102, 102, 255));
        show_mobile_data_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(show_mobile_data_Table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );

        bg_panel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 570, 600));

        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bg_panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 118, 1130, 10));

        logo_label.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        logo_label.setForeground(new java.awt.Color(255, 255, 255));
        logo_label.setText("SOLD MOBILES RECORD");
        logo_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logo_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logo_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logo_labelMouseExited(evt);
            }
        });
        bg_panel1.add(logo_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(54, 33, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Mobile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        imei_input.setBackground(new java.awt.Color(54, 33, 80));
        imei_input.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        imei_input.setForeground(new java.awt.Color(255, 255, 255));
        imei_input.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        imei_input.setCaretColor(new java.awt.Color(255, 255, 255));
        imei_input.setOpaque(false);
        imei_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                imei_inputKeyPressed(evt);
            }
        });

        search_button.setForeground(new java.awt.Color(51, 51, 51));
        search_button.setText("SEARCH");
        search_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        search_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_buttonMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("IMEI NO :-");

        total_number_of_mobiles_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_number_of_mobiles_label.setForeground(new java.awt.Color(255, 255, 255));

        count_mobiles_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        count_mobiles_label.setForeground(new java.awt.Color(255, 51, 102));

        delete_button.setForeground(new java.awt.Color(51, 51, 51));
        delete_button.setText("DELETE");
        delete_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        delete_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_buttonMouseClicked(evt);
            }
        });

        refresh_button.setForeground(new java.awt.Color(51, 51, 51));
        refresh_button.setText("REFRESH");
        refresh_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        refresh_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refresh_buttonMouseClicked(evt);
            }
        });

        select_all_check_box.setBackground(new java.awt.Color(54, 33, 80));
        select_all_check_box.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        select_all_check_box.setForeground(new java.awt.Color(255, 255, 255));
        select_all_check_box.setText("SELECT ALL");
        select_all_check_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_all_check_boxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(total_number_of_mobiles_label, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(count_mobiles_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(select_all_check_box)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imei_input, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(refresh_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imei_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(select_all_check_box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(total_number_of_mobiles_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(count_mobiles_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refresh_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        bg_panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 490, 290));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        bg_panel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 13, 590));

        jPanel4.setBackground(new java.awt.Color(54, 33, 80));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(255, 255, 255)));

        minimize_panel.setBackground(new java.awt.Color(54, 33, 80));

        minimize_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_minus_math_filled_25px.png"))); // NOI18N
        minimize_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize_labelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout minimize_panelLayout = new javax.swing.GroupLayout(minimize_panel);
        minimize_panel.setLayout(minimize_panelLayout);
        minimize_panelLayout.setHorizontalGroup(
            minimize_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimize_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize_label))
        );
        minimize_panelLayout.setVerticalGroup(
            minimize_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimize_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize_label))
        );

        jPanel4.add(minimize_panel);

        exit_panel.setBackground(new java.awt.Color(54, 33, 80));
        exit_panel.setLayout(new javax.swing.BoxLayout(exit_panel, javax.swing.BoxLayout.LINE_AXIS));

        exit_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_multiply_filled_25px.png"))); // NOI18N
        exit_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_labelMouseExited(evt);
            }
        });
        exit_panel.add(exit_label);

        jPanel4.add(exit_panel);

        bg_panel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_details_pane_70px.png"))); // NOI18N
        bg_panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        back_button_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8_circled_left_2_filled_50px.png"))); // NOI18N
        back_button_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_button_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_button_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_button_labelMouseExited(evt);
            }
        });
        bg_panel1.add(back_button_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logo_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo_labelMouseEntered
        // TODO add your handling code here:
        setColor(logo_label);
    }//GEN-LAST:event_logo_labelMouseEntered

    private void logo_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo_labelMouseExited
        // TODO add your handling code here:
        resetColor(logo_label);
    }//GEN-LAST:event_logo_labelMouseExited

    private void imei_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imei_inputKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            DefaultTableModel model = (DefaultTableModel)show_mobile_data_Table.getModel();
            model.setRowCount(0);
            if (imei_input.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(rootPane, "Please Fill Field");
            }
            else
            {
                show_Sold_MobileData_by_IMEI();
                EmptyFields();
            }
        }
    }//GEN-LAST:event_imei_inputKeyPressed

    private void search_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_buttonMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)show_mobile_data_Table.getModel();
        model.setRowCount(0);
        if (imei_input.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(rootPane, "Please Fill Field");
            }
            else
            {
                show_Sold_MobileData_by_IMEI();
                EmptyFields();
            }
    }//GEN-LAST:event_search_buttonMouseClicked

    private void minimize_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_labelMouseClicked

    private void minimize_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseEntered
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_minus_25px.png"));
        this.minimize_label.setIcon(icon);
    }//GEN-LAST:event_minimize_labelMouseEntered

    private void minimize_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_labelMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_minus_math_filled_25px.png"));
        this.minimize_label.setIcon(icon);
    }//GEN-LAST:event_minimize_labelMouseExited

    private void exit_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_labelMouseClicked

    private void exit_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseEntered
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/close.png"));
        this.exit_label.setIcon(icon);
    }//GEN-LAST:event_exit_labelMouseEntered

    private void exit_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_multiply_filled_25px.png"));
        this.exit_label.setIcon(icon);
    }//GEN-LAST:event_exit_labelMouseExited

    private void back_button_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button_labelMouseClicked
        // TODO add your handling code here:
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_back_button_labelMouseClicked

    private void delete_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_buttonMouseClicked
        // TODO add your handling code here:
        if(show_mobile_data_Table.getSelectionModel().isSelectionEmpty() && select_all_check_box.isSelected() == false)
        {
            JOptionPane.showMessageDialog(rootPane, "Select any one row from Table");
        }
        else
        {
            delete_all_Sold_Mobiles();
            EmptyFields();
        }
    }//GEN-LAST:event_delete_buttonMouseClicked

    private void refresh_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh_buttonMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)show_mobile_data_Table.getModel();
        model.setRowCount(0);
        show_Sold_Mobile_Data();
        EmptyFields();
    }//GEN-LAST:event_refresh_buttonMouseClicked

    private void back_button_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button_labelMouseEntered
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_circled_left_2_filled_50px_1.png"));
        this.back_button_label.setIcon(icon);
    }//GEN-LAST:event_back_button_labelMouseEntered

    private void back_button_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button_labelMouseExited
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/com/images/icons8_circled_left_2_filled_50px.png"));
        this.back_button_label.setIcon(icon);
    }//GEN-LAST:event_back_button_labelMouseExited

    private void select_all_check_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_all_check_boxActionPerformed
        // TODO add your handling code here:
        if(select_all_check_box.isSelected())
        {
        show_mobile_data_Table.selectAll();
        }
        else if(select_all_check_box.isSelected() == false)
        {
            show_mobile_data_Table.getSelectionModel().clearSelection(); 
        }
    }//GEN-LAST:event_select_all_check_boxActionPerformed

     public void setColor(JLabel label) 
    {
        label.setForeground(new java.awt.Color(231, 33, 99));
    }
    
    public void resetColor(JLabel label) 
    {
        label.setForeground(new java.awt.Color(255,255,255));
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Sold_Mobiles_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Sold_Mobiles_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Sold_Mobiles_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Sold_Mobiles_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Sold_Mobiles_Frame().setVisible(true);
//            }
//        });
//    }
    
                 //     ********------SOLD MOBILE DATA---MANAGEMENT---METHOD------********
    
    
    //SHOWING SOLD MOBILE DATA
     private void show_Sold_Mobile_Data(){
         List<Mobile_DataModel> mobile_DataModels = DBManager.getAllSoldMobiles();
         
         int count = mobile_DataModels.size();
         if(count > 0)
         {
             total_number_of_mobiles_label.setText("Total Number Of Mobiles :-");
             Border border = BorderFactory.createLineBorder(Color.WHITE, 2);
             count_mobiles_label.setBorder(border);
             count_mobiles_label.setText(" "+Integer.toString(count));
         }
         
         else
         {
            total_number_of_mobiles_label.setText("");
            count_mobiles_label.setBorder(null);
            count_mobiles_label.setText("");
            JOptionPane.showMessageDialog(rootPane, "You have no Sold Mobile data record.");  
         }
         
         DefaultTableModel model = (DefaultTableModel)show_mobile_data_Table.getModel();
         Object[] row = new Object[10];
         String sell = "SOLD";
         for(int i = 0;i<mobile_DataModels.size();i++){
             
            row[0] = sell;
            row[1] = mobile_DataModels.get(i).getModel_no();
            row[2] = mobile_DataModels.get(i).getBrand();
            row[3] = mobile_DataModels.get(i).getImei_no();
            row[4] = mobile_DataModels.get(i).getCost_price();
            row[5] = mobile_DataModels.get(i).getSale_price();
            row[6] = mobile_DataModels.get(i).getCondition();
            row[7] = mobile_DataModels.get(i).getDate();
            row[8] = mobile_DataModels.get(i).getColor();
            row[9] = mobile_DataModels.get(i).getModified_by();
            model.addRow(row);
         }
    }
     
     
        //SHOW SOLD MOBILE DATA BY IMEI NO
         private void show_Sold_MobileData_by_IMEI(){
         String imei = imei_input.getText().toUpperCase();
         List<Mobile_DataModel> mobile_DataModels = DBManager.getAllSoldMobilesByIMEI(imei);
         int count = mobile_DataModels.size();
         if(count > 0)
         {
             total_number_of_mobiles_label.setText("Total Number Of Mobiles :-");
             Border border = BorderFactory.createLineBorder(Color.WHITE, 2);
             count_mobiles_label.setBorder(border);
             count_mobiles_label.setText(" "+Integer.toString(count));
         }
         
         else
         {
            total_number_of_mobiles_label.setText("");
            count_mobiles_label.setText("");
            count_mobiles_label.setBorder(null);
            JOptionPane.showMessageDialog(rootPane, "You have no Sold Mobile data record according to your entered IMEI.");  
         }
         
         DefaultTableModel model = (DefaultTableModel)show_mobile_data_Table.getModel();
       
         Object[] row = new Object[10];
         String sell = "SOLD";
         for(int i = 0;i<mobile_DataModels.size();i++){
             
            row[0] = sell;
            row[1] = mobile_DataModels.get(i).getModel_no();
            row[2] = mobile_DataModels.get(i).getBrand();
            row[3] = mobile_DataModels.get(i).getImei_no();
            row[4] = mobile_DataModels.get(i).getCost_price();
            row[5] = mobile_DataModels.get(i).getSale_price();
            row[6] = mobile_DataModels.get(i).getCondition();
            row[7] = mobile_DataModels.get(i).getDate();
            row[8] = mobile_DataModels.get(i).getColor();
            row[9] = mobile_DataModels.get(i).getModified_by();
            model.addRow(row);
         }
    }
      
    /*      
      //DELETING ONE SOLD MOBILE DATA
      private void delete_Sold_Mobile(){
        String imei_no = ((String)  show_mobile_data_Table.getValueAt(show_mobile_data_Table.getSelectedRow(), 3));
        int row = DBManager.deleteMobile(imei_no);
        if (row > 0)
        {
                JOptionPane.showMessageDialog(null, "RECORD DELETED SUCCESSFULLY");
                DefaultTableModel model = (DefaultTableModel) show_mobile_data_Table.getModel();
                model.setRowCount(0);
                show_Sold_Mobile_Data();
        }
            else
        {
                JOptionPane.showMessageDialog(null, "RECORD NOT DELETED");
        }
    }
     */  
      
       //DELETING ALL SOLD MOBILE DATA
      private void delete_all_Sold_Mobiles() 
      {
              List<String> all_sold_mobiles_imei_no = new ArrayList(show_mobile_data_Table.getRowCount());
              int[] selected_rows = show_mobile_data_Table.getSelectedRows();
              for (int i = 0 ; i < selected_rows.length ; i++)
              {
                  all_sold_mobiles_imei_no.add(show_mobile_data_Table.getValueAt(selected_rows[i], 3).toString());
              }
      
              int row = DBManager.deleteAllSoldMobiles(all_sold_mobiles_imei_no);
      
              if (row > 0) 
              {
                  JOptionPane.showMessageDialog(null, "RECORD DELETED SUCCESSFULLY"); 
                  DefaultTableModel model = (DefaultTableModel) show_mobile_data_Table.getModel();
                  model.setRowCount(0);
                  show_Sold_Mobile_Data();
              }
              
              else
              {
                  JOptionPane.showMessageDialog(null, "RECORD NOT DELETED");
              }
      
      }
      
         
         //EMPTY FIELDS
       
       private void EmptyFields()
       {
            imei_input.setText("");
       }
       
        // SETTING UP WINDOWS ICON
        
       private void setIcon() 
        {
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/images/application_logo.png")));
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_button_label;
    private javax.swing.JPanel bg_panel1;
    private javax.swing.JLabel count_mobiles_label;
    private keeptoo.KButton delete_button;
    private javax.swing.JLabel exit_label;
    private javax.swing.JPanel exit_panel;
    private javax.swing.JTextField imei_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel logo_label;
    private javax.swing.JLabel minimize_label;
    private javax.swing.JPanel minimize_panel;
    private keeptoo.KButton refresh_button;
    private keeptoo.KButton search_button;
    private javax.swing.JCheckBox select_all_check_box;
    private javax.swing.JTable show_mobile_data_Table;
    private javax.swing.JLabel total_number_of_mobiles_label;
    // End of variables declaration//GEN-END:variables
}
